services:
    dead.console.controller:
        class: dead\console\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
    dead.console.listener:
        class: dead\console\event\main_listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
